# Generated by Django 4.0.4 on 2022-05-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingredient name', max_length=20)),
                ('type', models.CharField(max_length=10)),
                ('calories', models.IntegerField(help_text='Calories in 100g [g]')),
                ('fat', models.IntegerField(help_text='Fat in 100g [g]')),
                ('sodium', models.IntegerField(help_text='Sodium in 100g [mg]')),
                ('potasium', models.IntegerField(help_text='Potasium in 100g [mg]')),
                ('carbohydrates', models.IntegerField(help_text='Carbohydrates in 100g [mg]')),
                ('dietaryfiber', models.IntegerField(help_text='Dietary Fiber [g]')),
                ('sugar', models.IntegerField(help_text='Sugars in 100g [g]')),
                ('protein', models.IntegerField(help_text='Protein in 100g [g]')),
                ('vita', models.IntegerField()),
                ('vitc', models.IntegerField()),
                ('calcium', models.IntegerField()),
                ('iron', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
