# Generated by Django 4.0.4 on 2022-05-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_ingredient_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='fat',
            field=models.FloatField(help_text='Fat in 100g [g]'),
        ),
    ]
