# Generated by Django 4.0.4 on 2022-05-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_type_ingredient_phosphorous_ingredient_vitb6_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='iron',
            field=models.FloatField(),
        ),
    ]
